### ISSUE TITLE
Add profile info to the nightscout GitHub org

### ISSUE THREAD

**Issue by dandv** [nightscout/chrome-uploader#26]
https://github.com/nightscout looks bare. Compare to https://github.com/meteorpackaging/

**Comment by bewest** [comment]
Howdy @dandv , I'm closing this for now.  The point of the nightscout org is to host original sources making diabetes easier.

I think you are trying to make a [point](https://github.com/MeteorCommunity/discussions/issues/14) about process or community somehow.  Meta questions like this can be discussed with me, or you can open an issue on https://github.com/nightscout/process-controls, or https://github.com/nightscout/nightscout.github.io for more discussion.

**Comment by dandv** [comment]
Sorry for filing this in the wrong repo; I just couldn't figure out which one was more appropriate.

What I'm suggesting is adding some profile information to the GitHub org for users new to the umbrella of projects it hosts.
